### PR TITLE
Ky day 5 addon

### PR DESCRIPTION
**Pull request by KianYang-Lee**
Major revision of existing notebooks and inclusion of Exercise section for trainees.

### CODE REVIEW

**Comment by evanyeohboonkhai** [comment]
# 05 - Anomaly Detection Using Machine Learning Techniques
Found error in exercise part
image 

- **is the bonus cell will use by student ? If not please remove it** 



# 05 - Semi-supervised Anomaly Detection Using Convolutional Autoencoder
 
generate 33 samples of anomaly data that has uniform distribution in the range of 10 to 20
anomaly_data = np.random.uniform(low=15, high=25, size=(33, 1)) -> **comment is not same with code ,please check**


We can see from the statistics above that the mean for the data is 4.24, while standard deviation is 3.97. -> **the description is different from the code result**

Indeed, we can see that the mean and standard deviation of normal data are 2.95 and 0.95 respectively, fairly close to our expected values of 3 .-> **the description is different from the code result**


# 05 - Time Series Classification Using Deep Learning
Other than the initial and the final (window_size - 1) data values, all other data will appear in more than one of the sequences of data. Since we are trying to reconstruct a sequence of data, even if a sequence is identified as containing anomalous data, how can we know whether which data in the sequence is an anomaly? A simple way to solve this is to check for which of these data occurred in sequences that are all marked as anomalous. In our example above,...........-> **suggest breaking into paragraph or point form. to lengthy to read**

**Do you have a slide explain about nn.BCEWithLogitsLoss ? found that lack of comment and explanation in the notebook**


# 05 - Time Series Classification Using Machine Learning Techniques
b. Time Series Forest 
............ More information A time series -> **why capital A is here?**

Thanks, for the effort, overall is good to read, clean code, and easy to understand.
@KianYang-Lee

**Comment by KianYang-Lee** [comment]
Thanks @evanyeohboonkhai for the valuable input. I have made necessary corrections.

**Review by scot-certifai — APPROVED** [review]
Approving this with a presumption that technically all is good. Will be pulling all the code in the repo for a major grammatical review soon. Thanks KY!

**Comment by KianYang-Lee** [comment]
Noted with thanks @scot-certifai, can you do a merge on it too?

**Pull request merged**
