### PR TITLE
BK - Day3 - addition

### PR DESCRIPTION
**Pull request by evanyeohboonkhai**

### CODE REVIEW

**Comment by evanyeohboonkhai** [comment]
Hi team @KianYang-Lee @scot-certifai, please have a view on the addition Recap Exercise. Thanks

**Review by KianYang-Lee — COMMENTED** [review]
Please rename the file, there is a unnecessary space behind Exercise 

Interesting opening diagram, but looks like you are not giving any context to the diagram? If you are not using it, maybe to remove it? Else, can give 1 to 2 sentences for explanation?

Saw a lot of new terms being introduced here, eg. `SEMA` 

Not sure why ARIMA(5,1,1) is used, maybe can explain?

Don't think data_module is good to be used for revision since we are not providing them to use in exam anyway.

**Comment by evanyeohboonkhai** [comment]
1. The open diagram just wants to show the student overflow when the student builds the forecast algorithms from scratch.
2.   The parameter of choosing ARIMA(5,1,1) is determined and explain here
image
3. The intention of including the data_module is to show the students how they can use the Python module although it does not come out in the exam but just for extra knowledge.
4.  Referencing Mr Jason B. book because the sliding window function is taken from his book.
5.  It is not wise to separate the recap exercise since it is to recap everything. Furthermore, this exercise is to mimic a real world scenario when a student wants to handle time-series data

**Review by fareezjusman-skymind — COMMENTED** [review]
Very good exercise to rewind back the first 3 days TS coding practical. This exercise has a good flow with clear explanations. Good job BK for the excellent work. 

I just realize that in the problem statement, there is a missing words. 
image
 should be "dataset that measures the milk production(pounds per cow) as per month from January 1962 to December 1975" rite?

**Comment by evanyeohboonkhai** [comment]
fix typo and remove the notes to standardize with other notebooks. Thanks for the reviewing @fareezjusman-skymind

**Review by fareezjusman-skymind — APPROVED** [review]
Everything is good. Excellent work BK.

**Pull request merged**
